workflows:
  react-native-ios:
    name: Pound Drop iOS Build - iOS 18 SDK
    max_build_duration: 120
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: codemagic
    environment:
      ios_signing:
        certificates:
          - pound-drop-ios-distribution
        provisioning_profiles:
          - pound-drop-app-store-profile
      vars:
        BUNDLE_ID: "com.lifeguidancewithjesper.pounddrop"
        APPLE_TEAM_ID: "8VKM26D99V"
        XCODE_WORKSPACE: "PoundDrop.xcworkspace"
        XCODE_SCHEME: "PoundDrop"
        # Force Xcode 16.4 for iOS 18 SDK compliance
        XCODE_VERSION: "16.4"
        # Build from repository root
        CM_BUILD_DIR: "."
    scripts:
      - name: Install Node dependencies
        script: |
          echo "Installing Expo CLI and dependencies..."
          npm install -g @expo/cli@latest
          cp package-mobile.json package.json
          npm install
          
      - name: Fix Expo dependencies  
        script: |
          npx expo install --fix
          npx expo-doctor || echo "Expo doctor completed"
          
      - name: Prebuild iOS project
        script: |
          npx expo prebuild --platform ios --clean
          
      - name: Set up code signing
        script: |
          keychain add-certificates
          xcode-project use-profiles
          
      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install --clean-install
          
      - name: Build iOS app for App Store
        script: |
          xcode-project build-ipa \
            --workspace "ios/$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME" \
            --config "Release"
            
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      
    publishing:
      email:
        recipients:
          - jesper@lifeguidancewithjesper.com
        notify:
          success: true
          failure: true
      app_store_connect:
        auth: integration
        
  android:
    name: Pound Drop Android Build
    max_build_duration: 120
    instance_type: linux_x2
    environment:
      android_signing:
        - keystore_reference
      vars:
        CM_BUILD_DIR: "./mobile-app/pound-drop-fresh"
      groups:
        - google_play_credentials
    scripts:
      - name: Install Node dependencies
        script: |
          cd mobile-app/pound-drop-fresh
          npm ci
          
      - name: Build Android APK/AAB
        script: |
          cd mobile-app/pound-drop-fresh
          npx expo build:android --type app-bundle
          
    artifacts:
      - mobile-app/pound-drop-fresh/build/**/*.aab
      - mobile-app/pound-drop-fresh/build/**/*.apk
