workflows:
  react-native-ios:
    name: Pound Drop iOS - Clean Build
    max_build_duration: 120
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: codemagic
    environment:
      ios_signing:
        certificates:
          - pound-drop-ios-distribution
        provisioning_profiles:
          - pound-drop-app-store-profile
      vars:
        BUNDLE_ID: "com.lifeguidancewithjesper.pounddrop"
        APPLE_TEAM_ID: "8VKM26D99V"
        XCODE_VERSION: "16.4"
    scripts:
      - name: Install dependencies
        script: |
          npm install
          npx expo install --fix
          
      - name: Prebuild iOS
        script: |
          npx expo prebuild --platform ios --clean
          
      - name: Install CocoaPods
        script: |
          cd ios && pod install --clean-install && cd ..
          
      - name: Build iOS app for App Store  
        script: |
          # Ensure we're at repo root
          pwd
          # Locate generated workspace
          WORKSPACE=$(ls ios/*.xcworkspace | head -n1)
          if [ -z "$WORKSPACE" ]; then echo "No .xcworkspace found under ios/"; exit 1; fi
          echo "Using workspace: $WORKSPACE"

          # Derive scheme from workspace (first listed scheme)
          SCHEME=$(xcodebuild -list -workspace "$WORKSPACE" | awk '/Schemes:/{flag=1;next}/^\s*$/{if(flag){exit}}flag' | head -1 | xargs)
          if [ -z "$SCHEME" ]; then echo "No scheme found in $WORKSPACE"; exit 1; fi
          echo "Using scheme: $SCHEME"

          # Code signing and build
          keychain add-certificates
          xcode-project use-profiles
          xcode-project build-ipa \
            --workspace "$WORKSPACE" \
            --scheme "$SCHEME" \
            --config "Release"
            
    artifacts:
      - build/ios/ipa/*.ipa
      
    publishing:
      app_store_connect:
        auth: integration
