workflows:
  ios-workflow:
    name: iOS Workflow 
    max_build_duration: 120
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: Codemagic
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.pounddrop.app2024
      vars:
        BUNDLE_ID: "com.pounddrop.app2024"
        XCODE_WORKSPACE: "PoundDrop.xcworkspace"
        XCODE_SCHEME: "PoundDrop"
        CM_BUILD_DIR: "./mobile-app/pound-drop-mobile"
      node: 18.17.0
      xcode: 16.4
      cocoapods: default
    scripts:
      - name: Set up iOS signing
        script: |
          echo $IOS_DISTRIBUTION_CERTIFICATE | base64 --decode > ios_distribution.p12
          security create-keychain -p "" ~/Library/Keychains/build.keychain
          security import ios_distribution.p12 -k ~/Library/Keychains/build.keychain -P "" -A
          security list-keychains -s ~/Library/Keychains/build.keychain
          security default-keychain ~/Library/Keychains/build.keychain
          security unlock-keychain -p "" ~/Library/Keychains/build.keychain
      - name: Install npm dependencies
        script: |
          cd $CM_BUILD_DIR
          npm ci
      - name: Install/fix Expo dependencies  
        script: |
          cd $CM_BUILD_DIR
          npx expo install --fix
      - name: Prebuild iOS project
        script: |
          cd $CM_BUILD_DIR
          npx expo prebuild --platform ios --clean
      - name: Install CocoaPods dependencies
        script: |
          cd $CM_BUILD_DIR/ios
          pod install --clean-install
      - name: Build iOS app for App Store
        script: |
          xcode-project build-ipa \
            --workspace "$CM_BUILD_DIR/ios/$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME" \
            --config "Release"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing:
      app_store_connect:
        auth: integration
        submit_to_app_store: false
