workflows:
  react-native-ios:
    name: Pound Drop iOS - Clean Build
    max_build_duration: 120
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: codemagic
    environment:
      ios_signing:
        certificates:
          - pound-drop-ios-distribution
        provisioning_profiles:
          - pound-drop-app-store-profile
      vars:
        BUNDLE_ID: "com.lifeguidancewithjesper.pounddrop"
        APPLE_TEAM_ID: "8VKM26D99V"
        XCODE_WORKSPACE: "PoundDrop.xcworkspace"
        XCODE_SCHEME: "PoundDrop"
        XCODE_VERSION: "16.4"
    scripts:
      - name: Install dependencies
        script: |
          npm install
          npx expo install --fix
          
      - name: Prebuild iOS
        script: |
          npx expo prebuild --platform ios --clean
          
      - name: Build iOS
        script: |
          keychain add-certificates
          xcode-project use-profiles
          cd ios && pod install --clean-install
          xcode-project build-ipa --workspace "ios/$XCODE_WORKSPACE" --scheme "$XCODE_SCHEME" --config "Release"
            
    artifacts:
      - build/ios/ipa/*.ipa
      
    publishing:
      app_store_connect:
        auth: integration
