workflows:
  react-native-ios:
    name: Pound Drop iOS Build - iOS 18 SDK
    max_build_duration: 120
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: codemagic
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.lifeguidancewithjesper.pounddrop
      vars:
        BUNDLE_ID: "com.lifeguidancewithjesper.pounddrop"
        APPLE_TEAM_ID: "8VKM26D99V"
        XCODE_WORKSPACE: "PoundDrop.xcworkspace"
        XCODE_SCHEME: "PoundDrop"
        # Force Xcode 16.4 for iOS 18 SDK compliance
        XCODE_VERSION: "16.4"
        # Build from repository root
        CM_BUILD_DIR: "."
    scripts:
      - name: Install Node dependencies
        script: |
          pwd
          ls -la
          echo "Looking for mobile app files..."
          find . -name "app.json" -type f
          find . -name "package.json" -type f  
          find . -name "package-lock.json" -type f
          echo "Checking if mobile-app directory exists..."
          ls -la mobile-app/ || echo "mobile-app directory not found"
          ls -la mobile-app/pound-drop-fresh/ || echo "mobile-app/pound-drop-fresh directory not found"
          npm install -g @expo/cli@latest
          npm install
