workflows:
  react-native-ios:
    name: Pound Drop iOS Build - iOS 18 SDK
    max_build_duration: 120
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: codemagic
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.lifeguidancewithjesper.pounddrop
        certificates:
          - pound-drop-ios-distribution
      vars:
        BUNDLE_ID: "com.lifeguidancewithjesper.pounddrop"
        APPLE_TEAM_ID: "8VKM26D99V"
        XCODE_WORKSPACE: "PoundDrop.xcworkspace"
        XCODE_SCHEME: "PoundDrop"
        XCODE_VERSION: "16.4"
        CM_BUILD_DIR: "."
    scripts:
      - name: Install Node dependencies
        script: |
          echo "Installing Expo CLI and dependencies..."
          npm install -g @expo/cli@latest
          npm install
          
      - name: Fix Expo dependencies  
        script: |
          npx expo install --fix
          npx expo-doctor || echo "Expo doctor completed"
          
      - name: Prebuild iOS project
        script: |
          npx expo prebuild --platform ios --clean
          
      - name: Add signing certificates to keychain
        script: |
          keychain add-certificates
          
      - name: Fetch/create signing files automatically
        script: |
          echo "Bundle ID: $BUNDLE_ID"
          echo "Team ID: $APPLE_TEAM_ID"
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create \
            --verbose \
            --log-api-calls
            
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
          
      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install --clean-install
          
      - name: Build iOS app for App Store
        script: |
          xcode-project build-ipa \
            --workspace "ios/$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME" \
            --configuration "Release" \
            --export-method app-store \
            --verbose
            
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      
    publishing:
      email:
        recipients:
          - jesper@lifeguidancewithjesper.com
        notify:
          success: true
          failure: true
      app_store_connect:
        auth: integration
