workflows:
  react-native-ios:
    name: Pound Drop iOS - Optimized Build
    max_build_duration: 60
    instance_type: mac_mini_m2_pro
    integrations:
      app_store_connect: codemagic
    cache:
      cache_paths:
        - $CM_BUILD_DIR/node_modules
        - ~/.npm
        - $CM_BUILD_DIR/ios/Pods
        - ~/Library/Caches/CocoaPods
    environment:
      ios_signing:
        certificates:
          - pound-drop-ios-distribution
        provisioning_profiles:
          - pound-drop-app-store-profile
      vars:
        BUNDLE_ID: "com.lifeguidancewithjesper.pounddrop"
        APPLE_TEAM_ID: "8VKM26D99V"
        XCODE_VERSION: "16.1"
        CM_BUILD_DIR: "./mobile-app/pound-drop-fresh"
    scripts:
      - name: Install dependencies (cached)
        script: |
          npm ci --legacy-peer-deps || npm install --legacy-peer-deps
          npx expo install --fix

      - name: Prebuild iOS (no clean)
        script: |
          export CI=1
          npx expo prebuild --platform ios --non-interactive

      - name: Set up code signing
        script: |
          keychain add-certificates
          xcode-project use-profiles

      - name: Install CocoaPods (optimized)
        script: |
          cd ios
          pod install

      - name: Build iOS app
        script: |
          WORKSPACE=$(find ios -name "*.xcworkspace" -print -quit)
          SCHEME=$(xcodebuild -list -workspace "$WORKSPACE" | grep -v "Pods-" | grep "PoundDrop" | head -n1)
          
          xcode-project build-ipa \
            --workspace "$WORKSPACE" \
            --scheme "$SCHEME" \
            --config Release

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        auth: integration
