workflows:
  react-native-ios:
    name: Pound Drop iOS Build - iOS 18 SDK
    max_build_duration: 120
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: codemagic
    environment:
      ios_signing:
        certificates:
          - pound-drop-ios-distribution
        provisioning_profiles:
          - pound-drop-app-store-profile
      vars:
        BUNDLE_ID: "com.lifeguidancewithjesper.pounddrop"
        APPLE_TEAM_ID: "8VKM26D99V"
        XCODE_WORKSPACE: "PoundDrop.xcworkspace"
        XCODE_SCHEME: "PoundDrop"
        XCODE_VERSION: "16.4"
        # Build from complete Expo project with babel.config.js
        CM_BUILD_DIR: "./mobile-app/pound-drop-fresh"
    scripts:
      - name: Install Node dependencies
        script: |
          echo "Building from complete Expo project with Metro configuration..."
          cd $CM_BUILD_DIR
          npm ci
          
      - name: Fix Expo dependencies  
        script: |
          cd $CM_BUILD_DIR
          npx expo install --fix
          npx expo-doctor || echo "Expo doctor completed"
          
      - name: Prebuild iOS project
        script: |
          cd $CM_BUILD_DIR
          npx expo prebuild --platform ios --clean
          
      - name: Set up code signing
        script: |
          keychain add-certificates
          xcode-project use-profiles
          
      - name: Install CocoaPods dependencies
        script: |
          cd $CM_BUILD_DIR/ios
          pod install --clean-install
          
      - name: Build iOS app for App Store
        script: |
          xcode-project build-ipa \
            --workspace "$CM_BUILD_DIR/ios/$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME" \
            --config "Release"
            
    artifacts:
      - mobile-app/pound-drop-fresh/build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      
    publishing:
      email:
        recipients:
          - jesper@lifeguidancewithjesper.com
        notify:
          success: true
          failure: true
      app_store_connect:
        auth: integration
