workflows:
  react-native-ios:
    name: Pound Drop iOS Build
    instance_type: mac_mini_m2
    max_build_duration: 120
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.lifeguidancewithjesper.pounddrop
      vars:
        BUNDLE_ID: com.lifeguidancewithjesper.pounddrop
        APPLE_TEAM_ID: "8VKM26D99V"
        XCODE_WORKSPACE: PoundDrop.xcworkspace
        XCODE_SCHEME: PoundDrop
    scripts:
      - name: Install dependencies
        script: |
          npm install -g @expo/cli
          npm ci
      - name: Prebuild iOS
        script: |
          npx expo prebuild --platform ios --clear
      - name: Initialize keychain
        script: keychain initialize
      - name: Fetch signing files (create if missing)
        script: |
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create \
            --team-id "$APPLE_TEAM_ID"
      - name: Add certificates to keychain
        script: keychain add-certificates
      - name: Use signing profiles
        script: xcode-project use-profiles
      - name: Build iOS
        script: |
          xcode-project build-ipa \
            --workspace "ios/$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME" \
            --config "Release" \
            --export-method app-store
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - jesper@lifeguidancewithjesper.com
        notify:
          success: true
          failure: true
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
